# Credit Risk Resampling Techniques

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV into DataFrame

In [3]:
# Load the data

file_path = Path('Resources/lending_data.csv')
df = pd.read_csv(file_path)
df.head()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672       own            52800        0.431818   
1     8400.0          6.692       own            43600        0.311927   
2     9000.0          6.963      rent            46100        0.349241   
3    10700.0          7.664       own            52700        0.430740   
4    10800.0          7.698  mortgage            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt loan_status  
0                5                 1       22800    low_risk  
1                3                 0       13600    low_risk  
2                3                 0       16100    low_risk  
3                5                 1       22700    low_risk  
4                5                 1       23000    low_risk

# Split the Data into Training and Testing

In [4]:
# # Create our features
# # YOUR CODE HERE

X = df.copy()
X = X.drop(columns="loan_status")
X = pd.get_dummies(X)

# # Create our target
# # YOUR CODE HERE

y = df[['loan_status']]

In [5]:
X.describe()

loan_size  interest_rate  borrower_income  debt_to_income  \
count  77536.000000   77536.000000     77536.000000    77536.000000   
mean    9805.562577       7.292333     49221.949804        0.377318   
std     2093.223153       0.889495      8371.635077        0.081519   
min     5000.000000       5.250000     30000.000000        0.000000   
25%     8700.000000       6.825000     44800.000000        0.330357   
50%     9500.000000       7.172000     48100.000000        0.376299   
75%    10400.000000       7.528000     51400.000000        0.416342   
max    23800.000000      13.235000    105200.000000        0.714829   

       num_of_accounts  derogatory_marks    total_debt  homeowner_mortgage  \
count     77536.000000      77536.000000  77536.000000        77536.000000   
mean          3.826610          0.392308  19221.949804            0.497472   
std           1.904426          0.582086   8371.635077            0.499997   
min           0.000000          0.000000      0.000000            0.000000   
25%           3.000000          0.000000  14800.000000            0.000000   
50%           4.000000          0.000000  18100.000000            0.000000   
75%           4.000000          1.000000  21400.000000            1.000000   
max          16.000000          3.000000  75200.000000            1.000000   

       homeowner_own  homeowner_rent  
count   77536.000000    77536.000000  
mean        0.398911        0.103616  
std         0.489678        0.304764  
min         0.000000        0.000000  
25%         0.000000        0.000000  
50%         0.000000        0.000000  
75%         1.000000        0.000000  
max         1.000000        1.000000

In [6]:
y.describe()

loan_status
count        77536
unique           2
top       low_risk
freq         75036

In [7]:
y.head()

loan_status
0    low_risk
1    low_risk
2    low_risk
3    low_risk
4    low_risk

In [8]:
# Check the balance of our target values

y['loan_status'].value_counts()

low_risk     75036
high_risk     2500
Name: loan_status, dtype: int64

In [9]:
# Create X_train, X_test, y_train, y_test
# YOUR CODE HERE

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

X_train.shape

(58152, 10)

In [10]:
X_train

loan_size  interest_rate  borrower_income  debt_to_income  \
25729    10100.0          7.402            50300        0.403579   
20176     9200.0          7.049            46900        0.360341   
55080     8800.0          6.870            45200        0.336283   
10410     8900.0          6.919            45700        0.343545   
63110     8500.0          6.731            43900        0.316629   
...          ...            ...              ...             ...   
4767     12300.0          8.346            59100        0.492386   
26012     8300.0          6.634            43000        0.302326   
58637     6700.0          5.988            36900        0.186992   
23339     9200.0          7.054            47000        0.361702   
45677     7600.0          6.352            40400        0.257426   

       num_of_accounts  derogatory_marks  total_debt  homeowner_mortgage  \
25729                4                 1       20300                   1   
20176                3                 0       16900                   1   
55080                3                 0       15200                   1   
10410                3                 0       15700                   1   
63110                3                 0       13900                   0   
...                ...               ...         ...                 ...   
4767                 6                 1       29100                   1   
26012                2                 0       13000                   0   
58637                1                 0        6900                   1   
23339                3                 0       17000                   1   
45677                2                 0       10400                   1   

       homeowner_own  homeowner_rent  
25729              0               0  
20176              0               0  
55080              0               0  
10410              0               0  
63110              1               0  
...              ...             ...  
4767               0               0  
26012              1               0  
58637              0               0  
23339              0               0  
45677              0               0  

[58152 rows x 10 columns]

In [11]:
X_test

loan_size  interest_rate  borrower_income  debt_to_income  \
37214    11500.0          8.017            56000        0.464286   
2791      9700.0          7.227            48600        0.382716   
75901    16900.0         10.312            77600        0.613402   
70752    10600.0          7.632            52400        0.427481   
54071    11300.0          7.936            55300        0.457505   
...          ...            ...              ...             ...   
18042     7700.0          6.394            40800        0.264706   
31124    11300.0          7.911            55000        0.454545   
37300    11000.0          7.812            54100        0.445471   
33961    11100.0          7.857            54500        0.449541   
33499    10200.0          7.453            50700        0.408284   

       num_of_accounts  derogatory_marks  total_debt  homeowner_mortgage  \
37214                5                 1       26000                   0   
2791                 4                 0       18600                   1   
75901               10                 2       47600                   0   
70752                5                 1       22400                   1   
54071                5                 1       25300                   1   
...                ...               ...         ...                 ...   
18042                2                 0       10800                   0   
31124                5                 1       25000                   0   
37300                5                 1       24100                   0   
33961                5                 1       24500                   1   
33499                4                 1       20700                   1   

       homeowner_own  homeowner_rent  
37214              1               0  
2791               0               0  
75901              1               0  
70752              0               0  
54071              0               0  
...              ...             ...  
18042              1               0  
31124              1               0  
37300              1               0  
33961              0               0  
33499              0               0  

[19384 rows x 10 columns]

In [12]:
y_train

loan_status
25729    low_risk
20176    low_risk
55080    low_risk
10410    low_risk
63110    low_risk
...           ...
4767     low_risk
26012    low_risk
58637    low_risk
23339    low_risk
45677    low_risk

[58152 rows x 1 columns]

In [13]:
y_test

loan_status
37214    low_risk
2791     low_risk
75901   high_risk
70752    low_risk
54071    low_risk
...           ...
18042    low_risk
31124    low_risk
37300    low_risk
33961    low_risk
33499    low_risk

[19384 rows x 1 columns]

In [14]:
# name_to_num = {name: num for num, name in enumerate(calendar.month_name) if num}
# name_to_num

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [15]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler

# YOUR CODE HERE
scaler = StandardScaler()

In [16]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
# YOUR CODE HERE

X_scaler = scaler.fit(X_train)

In [17]:
# Scale the training and testing data
# YOUR CODE HERE

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
results = []

# Simple Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [20]:
# Calculated the balanced accuracy score

from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9543211898288821

In [21]:
# Display the confusion matrix

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[  571,    54],
       [   93, 18666]], dtype=int64)

In [22]:
# Print the imbalanced classification report

#!pip install imblearn
from imblearn.metrics import classification_report_imbalanced
r = classification_report_imbalanced(y_test, y_pred, output_dict=True)
r2 = pd.DataFrame(r)
ret = dict(r2.loc["pre"])
ret["ML"] = "LogisticRegression"
ret["Score"] = balanced_accuracy_score(y_test, y_pred)
ret
results.append(ret)

# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

Naive Random Oversampling### Naive Random Oversampling

In [23]:
# Resample the training data with the RandomOversampler
# YOUR CODE HERE

from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

# View the count of target classes with Counter
# YOUR CODE HERE

from collections import Counter

Counter(y_resampled)

Counter({'loan_status': 1})

In [24]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [25]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.9543211898288821

In [26]:
# Display the confusion matrix
# YOUR CODE HERE

from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[  622,     3],
       [  106, 18653]], dtype=int64)

In [27]:
# Print the imbalanced classification report
# YOUR CODE HERE

from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.85      1.00      0.99      0.92      0.99      0.99       625
   low_risk       1.00      0.99      1.00      1.00      0.99      0.99     18759

avg / total       1.00      0.99      1.00      0.99      0.99      0.99     19384



In [28]:
r = classification_report_imbalanced(y_test, y_pred, output_dict=True)
r2 = pd.DataFrame(r)
ret = dict(r2.loc["pre"])
# t["ML"] = "LogisticRegression+RandomOverSampler"
ret["ML"] = "Naive Random Oversampling"
ret["Score"] = balanced_accuracy_score(y_test, y_pred)
ret
results.append(ret)

In [29]:
# Table to track results
pd.DataFrame(results)

high_risk  low_risk   avg_pre   avg_rec   avg_spe    avg_f1   avg_geo  \
0   0.859940  0.997115  0.992692  0.992416  0.916226  0.992527  0.953452   
1   0.854396  0.999839  0.995150  0.994377  0.995173  0.994583  0.994775   

    avg_iba  total_support                         ML     Score  
0  0.915997        19384.0         LogisticRegression  0.954321  
1  0.989498        19384.0  Naive Random Oversampling  0.994775

### SMOTE Oversampling

In [30]:
# Resample the training data with SMOTE
# YOUR CODE HERE

from imblearn.over_sampling import SMOTE

X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy=1.0).fit_resample(X_train, y_train)

# View the count of target classes with Counter
# YOUR CODE HERE

from collections import Counter

Counter(y_resampled)

Counter({'loan_status': 1})

In [31]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [32]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9948279972279972

In [33]:
# Display the confusion matrix
# YOUR CODE HERE

confusion_matrix(y_test, y_pred)

array([[  622,     3],
       [  104, 18655]], dtype=int64)

In [34]:
# Print the imbalanced classification report
# YOUR CODE HERE

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.86      1.00      0.99      0.92      0.99      0.99       625
   low_risk       1.00      0.99      1.00      1.00      0.99      0.99     18759

avg / total       1.00      0.99      1.00      0.99      0.99      0.99     19384



In [35]:
r = classification_report_imbalanced(y_test, y_pred, output_dict=True)
r2 = pd.DataFrame(r)
ret = dict(r2.loc["pre"])
# ret["ML"] = "LogisticRegression+RandomOverSampler"
ret["ML"] = "SMOTE Oversampling"
ret["Score"] = balanced_accuracy_score(y_test, y_pred)
ret
results.append(ret)

In [36]:
pd.DataFrame(results)

high_risk  low_risk   avg_pre   avg_rec   avg_spe    avg_f1   avg_geo  \
0   0.859940  0.997115  0.992692  0.992416  0.916226  0.992527  0.953452   
1   0.854396  0.999839  0.995150  0.994377  0.995173  0.994583  0.994775   
2   0.856749  0.999839  0.995226  0.994480  0.995176  0.994679  0.994828   

    avg_iba  total_support                         ML     Score  
0  0.915997        19384.0         LogisticRegression  0.954321  
1  0.989498        19384.0  Naive Random Oversampling  0.994775  
2  0.989614        19384.0         SMOTE Oversampling  0.994828

# Undersampling

In this section, you will test an undersampling algorithm to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [37]:
# Resample the data using the ClusterCentroids resampler
# YOUR CODE HERE

# from imblearn.under_sampling import RandomUnderSampler
# ros = RandomUnderSampler(random_state=1)
# X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

from imblearn.under_sampling import ClusterCentroids

cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)

from collections import Counter

Counter(y_resampled)

# View the count of target classes with Counter
# YOUR CODE HERE

from collections import Counter

Counter(y_resampled)

Counter({'loan_status': 1})

In [38]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE

from sklearn.linear_model import LogisticRegression
model_cc = LogisticRegression(solver='lbfgs', random_state=1)
model_cc.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [39]:
# Calculate the balanced accuracy score
# YOUR CODE HERE

from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

y_pred_cc = model_cc.predict(X_test)
balanced_accuracy_score(y_test, y_pred_cc)

0.9836813049736126

In [40]:
# Display the confusion matrix
# YOUR CODE HERE

from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred_cc)

array([[  608,    17],
       [  102, 18657]], dtype=int64)

In [41]:
# Print the imbalanced classification report
# YOUR CODE HERE

from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred_cc))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.86      0.97      0.99      0.91      0.98      0.97       625
   low_risk       1.00      0.99      0.97      1.00      0.98      0.97     18759

avg / total       0.99      0.99      0.97      0.99      0.98      0.97     19384



In [42]:
r = classification_report_imbalanced(y_test, y_pred_cc, output_dict=True)
r2 = pd.DataFrame(r)
ret = dict(r2.loc["pre"])
#ret["ML"] = "LogisticRegression+RandomOverSampler"
ret["ML"] = "Undersampling"
ret["Score"] = balanced_accuracy_score(y_test, y_pred)
ret
results.append(ret)

In [43]:
pd.DataFrame(results)

high_risk  low_risk   avg_pre   avg_rec   avg_spe    avg_f1   avg_geo  \
0   0.859940  0.997115  0.992692  0.992416  0.916226  0.992527  0.953452   
1   0.854396  0.999839  0.995150  0.994377  0.995173  0.994583  0.994775   
2   0.856749  0.999839  0.995226  0.994480  0.995176  0.994679  0.994828   
3   0.856338  0.999090  0.994487  0.993861  0.973502  0.994049  0.983621   

    avg_iba  total_support                         ML     Score  
0  0.915997        19384.0         LogisticRegression  0.954321  
1  0.989498        19384.0  Naive Random Oversampling  0.994775  
2  0.989614        19384.0         SMOTE Oversampling  0.994828  
3  0.969480        19384.0              Undersampling  0.994828

# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [44]:
# Resample the training data with SMOTEENN
# YOUR CODE HERE

from imblearn.combine import SMOTEENN

smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)

# View the count of target classes with Counter
# YOUR CODE HERE

Counter(y_resampled)

Counter({'loan_status': 1})

In [45]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [46]:
# Calculate the balanced accuracy score
# YOUR CODE HERE

from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.9948279972279972

In [47]:
# Display the confusion matrix
# YOUR CODE HERE

from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[  622,     3],
       [  107, 18652]], dtype=int64)

In [48]:
# Print the imbalanced classification report
# YOUR CODE HERE

from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.85      1.00      0.99      0.92      0.99      0.99       625
   low_risk       1.00      0.99      1.00      1.00      0.99      0.99     18759

avg / total       1.00      0.99      1.00      0.99      0.99      0.99     19384



In [49]:
r = classification_report_imbalanced(y_test, y_pred_cc, output_dict=True)
r2 = pd.DataFrame(r)
ret = dict(r2.loc["pre"])
#ret["ML"] = "LogisticRegression+RandomOverSampler"
ret["ML"] = "Combination over and under sampling"
ret["Score"] = balanced_accuracy_score(y_test, y_pred)
ret
results.append(ret)

In [50]:
pd.DataFrame(results)

high_risk  low_risk   avg_pre   avg_rec   avg_spe    avg_f1   avg_geo  \
0   0.859940  0.997115  0.992692  0.992416  0.916226  0.992527  0.953452   
1   0.854396  0.999839  0.995150  0.994377  0.995173  0.994583  0.994775   
2   0.856749  0.999839  0.995226  0.994480  0.995176  0.994679  0.994828   
3   0.856338  0.999090  0.994487  0.993861  0.973502  0.994049  0.983621   
4   0.856338  0.999090  0.994487  0.993861  0.973502  0.994049  0.983621   

    avg_iba  total_support                                   ML     Score  
0  0.915997        19384.0                   LogisticRegression  0.954321  
1  0.989498        19384.0            Naive Random Oversampling  0.994775  
2  0.989614        19384.0                   SMOTE Oversampling  0.994828  
3  0.969480        19384.0                        Undersampling  0.994828  
4  0.969480        19384.0  Combination over and under sampling  0.994748

# Final Questions

1. Which model had the best balanced accuracy score?

    The balanced accuracy in binary and multiclass classification problems to deal with imbalanced datasets. 
    It is defined as the average of recall obtained on each class. The best value is 1 and the worst value is 0 when adjusted=False.
    
    The best balanced accuracy score is the SMOTE Over and Undersampling

   
2. Which model had the best recall score?
  
    Smote Oversampling has the best recall score
    

3. Which model had the best geometric mean score?
    
    SMOTE Oversampling has the best geometric mean score
    
